"""Build the export adapter from a validated plan. DelegateDoctor writes it.

The agent never emits Python. It fills in `PreparationPlan`, every field of
which has already been checked to be a plain literal or an identifier, and the
template below turns that into source. Every value that reaches the file goes
through `repr()`, so even a value that slipped through validation would land as
data rather than as code.

The adapter runs in a child process (see `preparation.py`), exports the model,
and writes the `ExportedProgram` to a `.pt2` in a temporary directory. It is
the only file DelegateDoctor generates, and it is deleted after the run.
"""

from __future__ import annotations

from pathlib import Path

from .preparation_schema import PreparationPlan, TensorInputSpec

# What the child process prints on success, so the parent can tell a real
# result from incidental output the user's own module may have produced.
SUCCESS_MARKER = "DELEGATE_DOCTOR_EXPORT_OK"
FAILURE_MARKER = "DELEGATE_DOCTOR_EXPORT_FAILED"


def _tensor_expression(spec: TensorInputSpec) -> str:
    """One controlled `torch.<generator>(...)` call. No user text is inlined."""
    shape = ", ".join(str(int(dimension)) for dimension in spec.shape)
    dtype = f"torch.{spec.dtype}"

    if spec.generator == "randint":
        # randint needs bounds; a small range keeps index-like inputs valid.
        return f"torch.randint(0, 2, ({shape},), dtype={dtype})"
    if spec.generator == "arange":
        total = 1
        for dimension in spec.shape:
            total *= int(dimension)
        return (f"torch.arange({total}, dtype={dtype}).reshape({shape},)")
    if spec.generator in ("zeros", "ones", "empty"):
        return f"torch.{spec.generator}({shape}, dtype={dtype})"
    if spec.generator == "rand":
        return f"torch.rand({shape}, dtype={dtype})"
    return f"torch.randn({shape}, dtype={dtype})"


def build_adapter_source(plan: PreparationPlan, module_name: str,
                         source_dir: Path, output_path: Path) -> str:
    """The complete adapter, assembled from validated values only."""
    constructor_parts = [repr(value) for value in plan.constructor_args]
    constructor_parts += [f"{name}={value!r}"
                          for name, value in sorted(plan.constructor_kwargs.items())]
    constructor_call = ", ".join(constructor_parts)

    if plan.symbol_kind == "existing_instance":
        obtain_model = f"model = getattr(user_module, {plan.symbol!r})"
    else:
        obtain_model = (
            f"model_class = getattr(user_module, {plan.symbol!r})\n"
            f"    model = model_class({constructor_call})"
        )

    checkpoint_block = ""
    if plan.checkpoint:
        checkpoint_block = f"""
    checkpoint_path = SOURCE_DIR / {plan.checkpoint!r}
    if not checkpoint_path.is_file():
        fail("checkpoint not found beside the model source: "
             + checkpoint_path.name)
    # weights_only=True, with no fallback: DelegateDoctor will not unpickle
    # arbitrary objects out of a checkpoint on the user's behalf.
    state = torch.load(checkpoint_path, map_location="cpu", weights_only=True)
    if hasattr(state, "keys") and "state_dict" in state:
        state = state["state_dict"]
    model.load_state_dict(state)
"""

    positional = ", ".join(_tensor_expression(spec)
                           for spec in plan.positional_inputs)
    if positional:
        positional += ","
    keyword_items = ", ".join(
        f"{name!r}: {_tensor_expression(spec)}"
        for name, spec in sorted(plan.keyword_inputs.items()))

    return f'''"""Generated by DelegateDoctor from a validated preparation plan.

Temporary. Built from structured fields, not from AI-written source: every
value below came through `repr()` after schema validation.
"""

import sys
import traceback
from pathlib import Path

import torch

SOURCE_DIR = Path({str(source_dir)!r})
OUTPUT_PATH = Path({str(output_path)!r})

if str(SOURCE_DIR) not in sys.path:
    sys.path.insert(0, str(SOURCE_DIR))


def fail(message):
    print("{FAILURE_MARKER}")
    print(message)
    raise SystemExit(1)


def main():
    try:
        user_module = __import__({module_name!r})
    except ModuleNotFoundError as error:
        missing = getattr(error, "name", "") or str(error)
        fail("MISSING_DEPENDENCY:" + str(missing))
    except Exception:
        fail("IMPORT_FAILED:\\n" + traceback.format_exc(limit=6))

    {obtain_model}
{checkpoint_block}
    if not isinstance(model, torch.nn.Module):
        fail("The selected symbol is not a torch.nn.Module: "
             + type(model).__name__)

    model.eval()

    args = ({positional})
    kwargs = {{{keyword_items}}}

    try:
        with torch.no_grad():
            model(*args, **kwargs)
    except Exception:
        fail("FORWARD_FAILED:\\n" + traceback.format_exc(limit=6))

    try:
        exported = torch.export.export(model, args=args, kwargs=kwargs)
    except Exception:
        fail("EXPORT_FAILED:\\n" + traceback.format_exc(limit=8))

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    torch.export.save(exported, OUTPUT_PATH)
    torch.save((args, kwargs), OUTPUT_PATH.with_suffix(".inputs.pt"))
    print("{SUCCESS_MARKER}")


main()
'''


def summarize_plan(plan: PreparationPlan) -> str:
    """A privacy-safe summary, suitable for the console and for artifacts."""
    lines = [
        f"Model                   {plan.model_name}",
        f"Symbol                  {plan.symbol} ({plan.symbol_kind})",
    ]
    if plan.constructor_args or plan.constructor_kwargs:
        lines.append(f"Constructor             "
                     f"{len(plan.constructor_args)} positional, "
                     f"{len(plan.constructor_kwargs)} keyword")
    if plan.checkpoint:
        lines.append(f"Checkpoint              {plan.checkpoint}")
    if plan.describe_inputs():
        lines.append(f"Input                   {plan.describe_inputs()}")
    return "\n".join(lines)
